run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic

linters-settings:
  goimports:
    local-prefixes: github.com/mclemenceau/argus
